/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_yeguang_paramprotocol_ParamExecutor.h"


/*
 * Class:     com_yeguang_paramprotocol_ParamExecutor
 * Method:    AddFunction
 * Signature: (Lcom/yeguang/paramprotocol/ExecuteInterface;)V
 */
JNIEXPORT void JNICALL Java_com_yeguang_paramprotocol_ParamExecutor_AddFunction
  (JNIEnv *env, jobject obj, jobject executor)
{
    
}

