/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_yeguang_paramprotocol_ParamExecutor.h"
#include "ParamExecutor.h"
#include "JniCommon.h"

extern int JniRecvCallback(uint32_t function_id, yeguang::ParamArgs& args, void* context);

/*
 * Class:     com_yeguang_paramprotocol_ParamExecutor
 * Method:    AddFunction
 * Signature: (Ljava/lang/String;Lcom/yeguang/paramprotocol/ExecuteInterface;)V
 */
JNIEXPORT void JNICALL Java_com_yeguang_paramprotocol_ParamExecutor_AddFunction
  (JNIEnv *env, jobject obj, jstring funname, jobject executor)
{
	char *name = jstringTostring(env, funname);
	yeguang::ParamExecutor::Instance()->AddRecvCB(name, JniRecvCallback, executor);
	free(name);
}

