/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yeguang_paramprotocol_ParamExecutor */

#ifndef _Included_com_yeguang_paramprotocol_ParamExecutor
#define _Included_com_yeguang_paramprotocol_ParamExecutor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yeguang_paramprotocol_ParamExecutor
 * Method:    AddFunction
 * Signature: (Lcom/yeguang/paramprotocol/ExecuteInterface;)V
 */
JNIEXPORT void JNICALL Java_com_yeguang_paramprotocol_ParamExecutor_AddFunction
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
