/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yeguang_paramprotocol_ParamSocket */

#ifndef _Included_com_yeguang_paramprotocol_ParamSocket
#define _Included_com_yeguang_paramprotocol_ParamSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yeguang_paramprotocol_ParamSocket
 * Method:    Create
 * Signature: (Lcom/yeguang/paramprotocol/ParamCallback;)V
 */
JNIEXPORT void JNICALL Java_com_yeguang_paramprotocol_ParamSocket_Create
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_yeguang_paramprotocol_ParamSocket
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yeguang_paramprotocol_ParamSocket_Destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_yeguang_paramprotocol_ParamSocket
 * Method:    CheckConn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yeguang_paramprotocol_ParamSocket_CheckConn
  (JNIEnv *, jobject);

/*
 * Class:     com_yeguang_paramprotocol_ParamSocket
 * Method:    InputData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_yeguang_paramprotocol_ParamSocket_InputData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_yeguang_paramprotocol_ParamSocket
 * Method:    CallFunction
 * Signature: (Ljava/lang/String;Lcom/yeguang/paramprotocol/ParamArgs;)V
 */
JNIEXPORT void JNICALL Java_com_yeguang_paramprotocol_ParamSocket_CallFunction
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
